# Generated by Django 3.2.9 on 2021-11-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='rating_user',
            field=models.IntegerField(),
        ),
    ]
